name: flexs
channels:
  - bioconda
  - pytorch
  - https://levinthal:paradox@conda.graylab.jhu.edu
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py38h32f6830_1001
  - argon2-cffi=20.1.0=py38h4d0b108_1
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.1.5=pyh9f0ad1d_0
  - blosc=1.20.0=hb1e8313_0
  - bokeh=2.2.1=py38h32f6830_0
  - brotlipy=0.7.0=py38h64e0658_1000
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.1=py38hc4dd44e_0
  - chardet=3.0.4=py38h32f6830_1006
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.1=py38h52adbb4_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py38h0b31af3_0
  - dask=2.25.0=py_0
  - dask-core=2.25.0=py_0
  - dask-jobqueue=0.7.1=py_0
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.25.0=py38h32f6830_0
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.9=hb1e8313_2
  - freetype=2.10.2=h8da9a1a_0
  - fsspec=0.8.0=py_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - glib=2.65.0=h577aef8_0
  - heapdict=1.0.1=py_0
  - icu=67.1=hb1e8313_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=1.7.0=py38h32f6830_0
  - importlib_metadata=1.7.0=0
  - ipykernel=5.3.4=py38h23f93f0_0
  - ipython=7.18.1=py38h1cdfbd6_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.2=py38_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h0b31af3_0
  - json5=0.9.4=pyh9f0ad1d_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38h32f6830_1
  - jupyterlab=2.2.6=py_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.2.0=py38ha0d09dd_0
  - krb5=1.17.1=h75d18d8_3
  - lcms2=2.11=h174193d_0
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hf57f61e_1
  - libcxx=10.0.1=h5f48129_0
  - libedit=3.1.20191231=h0678c8f_2
  - libffi=3.2.1=hb1e8313_1007
  - libgfortran=4.0.0=3
  - libgfortran4=7.5.0=h1565451_3
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=h009f743_3
  - libopenblas=0.3.10=openmp_h63d9170_4
  - libpng=1.6.37=hb0a8c7a_2
  - libpq=12.3=h489d428_0
  - libsodium=1.0.18=h01d97ff_0
  - libtiff=4.1.0=h2ae36a8_6
  - libwebp-base=1.1.0=h0b31af3_3
  - llvm-openmp=10.0.1=h28b9765_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=hb1e8313_3
  - markupsafe=1.1.1=py38h64e0658_1
  - matplotlib=3.3.1=1
  - matplotlib-base=3.3.1=py38haed9462_1
  - mistune=0.8.4=py38h64e0658_1001
  - mkl=2020.2=260
  - msgpack-python=1.0.0=py38ha0d09dd_1
  - mysql-common=8.0.21=1
  - mysql-libs=8.0.21=hfb8f7af_1
  - nbconvert=5.6.1=py38h32f6830_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=hb1e8313_1
  - ninja=1.10.1=h879752b_1
  - notebook=6.1.3=py38h32f6830_0
  - nspr=4.20=h0a44026_1000
  - nss=3.47=hc0980d9_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=haf1e3a3_1
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.1=py38h11c0d25_0
  - pandoc=2.10.1=haf1e3a3_0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.44=h4a8c4bd_0
  - pexpect=4.8.0=py38h32f6830_1
  - pickleshare=0.7.5=py38h32f6830_1001
  - pillow=7.2.0=py38h83dc5e5_1
  - pip=20.2.2=py_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.7=py_0
  - prompt_toolkit=3.0.7=0
  - psutil=5.7.2=py38h4d0b108_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38hf180056_3
  - pyrosetta=2020.34+release.6dedbd4c240=py38_0
  - pyrsistent=0.16.0=py38h64e0658_0
  - pysocks=1.7.1=py38h32f6830_1
  - python=3.8.5=hfc71d35_7_cpython
  - python-blosc=1.9.1=py38h5fc983b_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.4.0=py3.8_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pyzmq=19.0.2=py38h2c785a9_0
  - qt=5.12.9=h717870c_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h0678c8f_2
  - requests=2.24.0=pyh9f0ad1d_0
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h32f6830_0
  - six=1.15.0=pyh9f0ad1d_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sqlite=3.33.0=h960bd1c_0
  - statsmodels=0.12.0=py38h4d0b108_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py38h32f6830_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py38_cpu
  - tornado=6.0.4=py38h64e0658_1
  - traitlets=4.3.3=py38h32f6830_1
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.10=py_0
  - viennarna=2.4.15=py38h026d7d4_0
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py38h32f6830_1
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.2=h4a8c4bd_3
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7795811_1009
  - zstd=1.4.5=h289c70a_2
  - pip:
    - absl-py==0.10.0
    - astunparse==1.6.3
    - biopython==1.78
    - boto3==1.14.56
    - botocore==1.17.56
    - cachetools==4.1.1
    - cloudpickle==1.3.0
    - dm-tree==0.1.5
    - docutils==0.15.2
    - editdistance==0.5.3
    - gast==0.3.3
    - gin-config==0.3.0
    - google-auth==1.21.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.31.0
    - h5py==2.10.0
    - jmespath==0.10.0
    - joblib==0.16.0
    - keras-preprocessing==1.1.2
    - lmdb==1.0.0
    - markdown==3.2.2
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pyyaml==5.3.1
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - s3transfer==0.3.3
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - tape-proteins==0.4
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - tensorflow==2.3.0
    - tensorflow-estimator==2.3.0
    - tensorflow-probability==0.11.0
    - termcolor==1.1.0
    - tf-agents==0.6.0
    - threadpoolctl==2.1.0
    - tqdm==4.48.2
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: /opt/anaconda3/envs/flexs
